NewSchoolApp/newschool-backend

.gitignore, .prettierrc, GUIDELINES.md, README.md, nest-cli.json, package-lock.json, package.json, src/CommonsModule/constants.ts, src/CommonsModule/entity/audit.entity.ts, src/CommonsModule/entity/index.ts, src/CommonsModule/index.ts, src/CommonsModule/mapper/index.ts, src/CommonsModule/mapper/mapper.ts, src/SecurityModule/controller/index.ts, src/SecurityModule/controller/security.controller.ts, src/SecurityModule/security.module.ts, src/SecurityModule/service/index.ts, src/SecurityModule/service/security.service.ts, src/app.controller.spec.ts, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/main.ts, test/app.e2e-spec.ts, test/jest-e2e.json, tsconfig.build.json, tsconfig.json, tslint.json
Mudanças:
- Criado um módulo de segurança (apenas como exemplo)
- Criado GUIDELINE.md para documentar como é estruturado o código
- Adicionado Swagger
=> Criar estrutura inicial

README.md
Colocado informações de como contribuir para o projeto.
=> Atualizado descrição do readme.

src/UserModule/entity/user.entity.ts, src/UserModule/repository/user.repository.ts, src/UserModule/service/user.service.ts, test/SecurityModule/security.e2e-spec.ts
- Gerando salt quando salva um usuário
- Salvando senha com hash no banco
- Validando se existe um usuário com o mesmo email antes de salvar
=> Senha com salt

package.json, src/CourseModule/entity/course.entity.ts, src/CourseModule/entity/index.ts, src/CourseModule/entity/lesson.entity.ts
Fechei o pull request antigo com o mesmo nome e abri esse novo, agora com as alterações sugeridas no outro e sem os commits que acabaram indo sem querer e que eram referentes à outra tarefa.
=> Criada entity de aulas e feito relacionamento da mesma com o curso

src/SecurityModule/controller/security.controller.ts, src/UserModule/controller/user.controller.ts, src/app.module.ts, src/config/database.ts, test/jest-e2e.json, test/jest.setup.ts
- log genérico vai ser o próprio log do Nest JS
- Adicionado configuração de log para o TypeORM
- Adicionado logs de teste
=> Log generico

src/SecurityModule/dto/index.ts, src/SecurityModule/dto/role.dto.ts, src/SecurityModule/index.ts, src/UserModule/controller/user.controller.ts, src/UserModule/dto/user-update.dto.ts, src/UserModule/dto/user.dto.ts, src/UserModule/service/user.service.ts, test/UserModule/user.e2e-spec.ts
- Arrumado testes
- Arrumado Swagger no /api/v1/user/me
=> Arrumando testes

src/scripts/dbScripts/change_password_creation#5.sql, src/scripts/dbScripts/client_credentials_creation#4.sql, src/scripts/dbScripts/course_table_creation#3.sql, src/scripts/dbScripts/role_table_creation#2.sql, src/scripts/dbScripts/user_table_creation#1.sql
Favor não fazer merge deste PR antes dos testes em ambiente DEV. Esta é a alteração para criação de padrões de scripts para banco de dados, futuramente serão usadas para implementação do FLYWAY.
O deploy correto deverá ser feito manualmente no banco de dados, quando o ambiente for publicado, farei a alteração no banco de dados manualmente.
CARD: https://trello.com/c/SUHuXrfb/48-cria%C3%A7%C3%A3o-de-padr%C3%A3o-de-scripts-para-cria%C3%A7%C3%A3o-manuten%C3%A7%C3%A3o-alimenta%C3%A7%C3%A3o-do-banco-de-dados
=> Fixing table creation scripts.

src/CourseModule/entity/course.entity.ts, src/CourseModule/entity/lesson.entity.ts, src/CourseModule/entity/part.entity.ts, src/UserModule/dto/user.dto.ts, src/UserModule/service/user.service.ts
- arrumando findById pra retornar as roles do usuário
- Arrumado UserDTO para referenciar RoleDTO
- Arrumado relacionamento de curso com lição
- Arrumado relacionamento de lição com curso
- Arrumado relacionamento de lição com parte
- Arrumado relacionamento de parte com lição
=> Arrumado /me não retornando role

src/UserModule/controller/user.controller.ts, src/UserModule/dto/index.ts, src/UserModule/dto/new-student.dto.ts, src/UserModule/dto/self-update.dto.ts, src/UserModule/service/user.service.ts
- Apenas ADMINS acessar o endpoint PUT /api/v1/user
- Apenas ADMINS podem mudar role dos usuários
- Adicionado endpoint PUT /me que altera a informação do usuário via jwt
=> Mudado forma de como os usuários dão update

src/UserModule/controller/user.controller.ts, src/UserModule/dto/admin-change-password.dto.ts, src/UserModule/dto/change-password.dto.ts, src/UserModule/dto/index.ts, src/UserModule/service/user.service.ts
- Criado endpoint PUT /api/v1/user/me/change-password para o usuário trocar a própria senha
- Criado endpoint PUT /api/v1/user/:id/change-password para admins trocarem a senha de qualquer usuário
=> Criado endpoints para alterar senha de usuário logado

src/CourseModule/dto/lesson-update.dto.ts, src/CourseModule/dto/lesson.dto.ts, src/CourseModule/dto/new-lesson.dto.ts, src/CourseModule/service/lesson.service.ts
- Corrigindo o bug 404 do lesson endpoint
- Adicionando Transactional
=> Corrigindo lesson endpoint

src/CourseModule/controllers/lesson.controller.ts, src/CourseModule/controllers/part.controller.ts, src/CourseModule/dto/new-part.dto.ts, src/CourseModule/dto/part-update.dto.ts, src/CourseModule/dto/part.dto.ts, src/CourseModule/service/lesson.service.ts, src/CourseModule/service/part.service.ts
- Ultimos ajustes Lesson Endpoint
- Corrigindo Part Endpoint
=> Fixing part endpoint

.github/workflows/ci.yml, LICENSE
Card: https://trello.com/c/KXBcAogf/79-implementar-ci-nas-prs-do-backend-para-validacao-de-testes-build-e-visualizacao-de-erros
=> Teste de Ci com GitHub actions

src/CourseModule/controllers/course.controller.ts, src/CourseModule/course.module.ts, src/CourseModule/dto/course.dto.ts, src/CourseModule/entity/course.entity.ts, src/CourseModule/service/course.service.ts, src/UploadModule/controllers/upload.controller.ts, src/UploadModule/upload.module.ts, src/UserModule/controller/user.controller.ts, src/config/database.ts
- Adicionado propriedade enabled pra deletar curso
- GetAll agora recebe enabled como parametro. Se não for passado, retorna todos os cursos, se for true, retorna os ativos, se for false, retorna os inativos.
- Aluno só pode ver cursos ativos
=> Adicionado propriedade enabled para deletar curso

src/CourseModule/controllers/course.controller.ts, src/CourseModule/dto/course.dto.ts, src/CourseModule/dto/new-course.dto.ts, src/CourseModule/entity/course.entity.ts, src/CourseModule/repository/course.repository.ts, src/CourseModule/service/course.service.ts, src/UserModule/controller/user.controller.ts, src/UserModule/entity/user.entity.ts, src/UserModule/service/user.service.ts
- Removido referência de curso com usuário para autor
- Adicionado campo authorName em curso
- Adicionado campo authorDescription em curso
closes #85
=> Trocado por referenciar usuario existente pra nome e descrição do autor

src/CourseTakenModule/controllers/course.taken.controller.ts, src/CourseTakenModule/service/course.taken.service.ts
Endpoint advance-on-course não estava retornando os objetos Lesson, Test e Part em seu corpo.
=> Correcao retorno do endpoint advance-on-courese

src/CourseTakenModule/course.taken.module.ts, src/CourseTakenModule/dto/attend.a.class.dto.ts, src/CourseTakenModule/service/course.taken.service.ts, src/UserModule/user.module.ts
=> AttendClass retornando UserDTO invés de User

src/CourseTakenModule/repository/course.taken.repository.ts
Correcao do endpoint course-taken/user/:user, agora está retornando a entidade Course no response body.
=> correcao_meus_cursos

src/CourseModule/dto/new-test.dto.ts, src/CourseModule/dto/test-update.dto.ts, src/CourseModule/dto/test.dto.ts, src/CourseModule/dto/test.without.correct.alternative.dto.ts, src/CourseModule/entity/test.entity.ts, src/CourseTakenModule/dto/attend.a.class.dto.ts
Correcao do campo que estava faltando na entidade test
=> Fixing course taken

src/CourseTakenModule/service/course.taken.service.ts
- Adicionando a feature refazer curso.
=> feature: refazer curso

src/CourseTakenModule/service/course.taken.service.ts
correção no arquivo course.taken.service.ts que estava dando a porcentagem incorreta do curso.
=> correção no arquivo course.taken.service.ts

src/CourseModule/controllers/test.controller.ts, src/CourseModule/dto/new-test.dto.ts, src/CourseModule/repository/test.repository.ts, src/CourseModule/service/test.service.ts
Fixes da issue #123
closes #123
=> Fixes adicionando test

src/CourseModule/controllers/part.controller.ts, src/CourseModule/dto/new-part.dto.ts, src/CourseModule/repository/part.repository.ts, src/CourseModule/service/part.service.ts
Fixes da issue #122
closes #122
=> Fixes adicionando part

src/ConfigModule/service/app-config.service.ts, src/CourseModule/entity/lesson.entity.ts, src/CourseModule/entity/part.entity.ts, src/CourseModule/entity/test.entity.ts, src/CourseModule/service/lesson.service.ts, src/CourseModule/service/part.service.ts, src/CourseModule/service/test.service.ts, src/CourseTakenModule/controllers/course.taken.controller.ts, src/CourseTakenModule/dto/advance-course.dto.ts, src/CourseTakenModule/dto/alternative-progression-data.dto.ts, src/CourseTakenModule/dto/alternative-progression.dto.ts, src/CourseTakenModule/dto/attend.a.class.dto.ts, src/CourseTakenModule/dto/course.taken-update.dto.ts, src/CourseTakenModule/dto/course.taken.dto.ts, src/CourseTakenModule/dto/current-progression.dto.ts, src/CourseTakenModule/dto/index.ts, src/CourseTakenModule/dto/my.courses.dto.ts, src/CourseTakenModule/dto/new-course.taken.dto.ts, src/CourseTakenModule/dto/video-progression-data.dto.ts, src/CourseTakenModule/dto/video-progression.dto.ts, src/CourseTakenModule/entity/course.taken.entity.ts, src/CourseTakenModule/enum/index.ts, src/CourseTakenModule/enum/step.enum.ts, src/CourseTakenModule/mapper/course.taken.mapper.ts, src/CourseTakenModule/repository/course.taken.repository.ts, src/CourseTakenModule/service/course.taken.service.ts, src/CourseTakenModule/swagger/course.taken-updated-info.swagger.ts
- Refatorado lógica de avanço do curso
- Criado endpoint de step atual do usuário
- Alterado url do endpoint para iniciar um course taken
=> Refactor nos métodos do wizard

src/CourseModule/controllers/test.controller.ts, src/CourseModule/service/test.service.ts
Fixes da issue #129
closes #129
=> Fixes check test

src/CourseModule/controllers/lesson.controller.ts, src/CourseModule/service/lesson.service.ts
Fixes da issue #124
closes #124
=> Fixes achar lessons por curso

src/CourseModule/entity/lesson.entity.ts, src/CourseModule/entity/part.entity.ts, src/CourseModule/entity/test.entity.ts, src/CourseTakenModule/entity/course.taken.entity.ts, src/CourseTakenModule/service/course.taken.service.ts
=> fix: fixed start course taken

src/DashboardModule/controller/dashboard.controller.ts, src/DashboardModule/controller/index.ts, src/DashboardModule/dashboard.module.ts, src/DashboardModule/index.ts, src/DashboardModule/service/dashboard.service.ts, src/DashboardModule/service/index.ts
Task no Trello: [Criar estrutura inicial do módulo de Dashboard](https://trello.com/c/c4GLtUyg/3-criar-estrutura-inicial-do-m%C3%B3dulo-de-dashboard)
Baseado na estrutura do projeto atual, foram criados:
- Módulo para Dashboard
- Service para Dashboard
- Controller para Dashboard
=> Adding dashboard module

src/CommonsModule/constants.ts, src/DashboardModule/controller/dashboard.controller.ts, src/DashboardModule/controller/index.ts, src/DashboardModule/dashboard.module.ts, src/DashboardModule/index.ts, src/DashboardModule/service/dashboard.service.ts, src/DashboardModule/service/index.ts, src/app.module.ts
- Criado DashboardModule
- Criado DashboardService
- Criado DashboardController
- Criado constante para nome do dashboard
=> feat: criado módulo de dashboard

.github/PULL_REQUEST_TEMPLATE/pull_request_feature.md, .gitignore, src/CourseTakenModule/repository/course.taken.repository.ts, src/CourseTakenModule/service/course.taken.service.ts, src/DashboardModule/controller/dashboard.controller.ts, src/DashboardModule/dto/certificate-quantity.dto.ts, src/DashboardModule/service/dashboard.service.ts, test/CourseTakenModule/course-taken.e2e-spec.ts, test/DashboardModule/dashboard.e2e-spec.ts, test/MessageModule/message.e2e-spec.ts
Adicionado endpoint pra pegar a quantidade de certificados
Selecione o que você fez
=> Adicionado endpoint para retornar a quantidade de certificados

src/SecurityModule/entity/client-credentials.entity.ts, src/SecurityModule/repository/client-credentials.repository.ts, src/SecurityModule/service/security.service.ts, test/CourseModule/course.e2e-spec.ts, test/CourseTakenModule/course-taken.e2e-spec.ts, test/DashboardModule/dashboard.e2e-spec.ts, test/MessageModule/message.e2e-spec.ts, test/SecurityModule/security.e2e-spec.ts, test/UploadModule/upload.e2e-spec.ts, test/UserModule/user.e2e-spec.ts
Adição de grant type no client credentials
=> :sparkles: Add grant type to client credentials

src/CourseModule/controllers/course.controller.ts, src/app.module.ts, test/CourseModule/course.e2e-spec.ts
Agora trás devidamente apenas os cursos com enabled true se o aluno quiser todos os cursos
=> fix: fixed user trying to get courses

src/UserModule/dto/new-student.dto.ts, src/UserModule/dto/new-user.dto.ts, src/UserModule/dto/user-update.dto.ts, src/UserModule/dto/user.dto.ts, src/UserModule/entity/user.entity.ts, src/UserModule/enum/user-profile.enum.ts, src/migration/1600564790819-User.ts, test/CourseTakenModule/course-taken.e2e-spec.ts, test/DashboardModule/dashboard.e2e-spec.ts, test/UserModule/user.e2e-spec.ts
=> CADASTRO BACK-END - PERFIL

src/UserModule/dto/new-student.dto.ts, src/UserModule/dto/new-user.dto.ts, src/UserModule/dto/user-update.dto.ts, src/UserModule/entity/user.entity.ts, src/migration/1600564790819-User.ts, src/migration/1600575537429-User.ts
Remoção dos campos que não sao utilizados no cadastro de alunos. 
=> remover campos cadastro aluno

src/UserModule/dto/new-student.dto.ts, src/UserModule/dto/new-user.dto.ts, src/UserModule/dto/user-update.dto.ts, src/UserModule/entity/user.entity.ts, src/migration/1600813620109-User.ts
=> mudança do institution name

test/DashboardModule/dashboard.e2e-spec.ts
Testes para o endpoint de requisitar cursos por frequência
=> test(dashboard): test from get courses by frequecy

src/ConfigModule/service/app-config.service.ts, src/migration/1600813620109-User.ts, test/DashboardModule/dashboard.e2e-spec.ts
SYNC_DATABASE agora só funciona em ambientes de testes
=> configuração SYNC_DATABASE só funciona em ambientes de teste

src/GameficationModule/gamefication.module.ts, src/GameficationModule/service/pusher.service.ts, src/GameficationModule/subscriber/achievement.subscriber.ts, src/NotificationModule/entity/notification.entity.ts, src/NotificationModule/enum/notification-type.enum.ts, src/NotificationModule/notification.module.ts, src/NotificationModule/repository/notification.repository.ts, src/NotificationModule/service/notification.service.ts, src/SecurityModule/repository/client-credentials.repository.ts, src/UserModule/entity/user.entity.ts, src/app.module.ts, src/migration/1601836666332-Notification.ts, src/migration/1601837424488-Notification.ts
Até o momento, as notificações para os usuários também serão criadas a partir de eventos do sistema. Atualmente, apenas a gameficação gera notificações
Proposta de arquitetura para notificação:
- As notificações possuem o mesmo conteúdo que os eventos que as criam, e.g: caso um evento de gameficação crie uma notificação, esse Achievement criado estará na propriedade "content" dentro da Notificação.
- Criado tabelas no banco de dados para notificação
Ainda veremos em como criar testes para notificação
=> Proposta Notificação

src/ConfigModule/service/app-config.service.ts, src/GameficationModule/entity/achievement.entity.ts, src/GameficationModule/entity/badge.entity.ts, src/GameficationModule/repository/achievement.repository.ts, src/GameficationModule/repository/badge.repository.ts, src/GameficationModule/service/course-rewards.service.ts, src/GameficationModule/subscriber/achievement.subscriber.ts, src/migration/1602969067980-Badge.ts, test/UserModule/user.e2e-spec.ts
Badges agora que tem os pontos dos achievements
=> Badges possuem pontos

src/GameficationModule/controller/gamefication.controller.ts, src/GameficationModule/enum/time-filter.enum.ts, src/GameficationModule/repository/achievement.repository.ts, src/GameficationModule/service/gamefication.service.ts
Feature onde criei as seguintes funcionalidades no gamefication module
Filtro anual,
Filtro Mensal,
Filtro por escola,
Filtro por cidade,
Filtro por estado
=> Feat: Ranking Filters

src/CourseModule/dto/nps-course-taken.dto.ts, src/CourseModule/service/course.taken.service.ts, src/GameficationModule/repository/achievement.repository.ts, src/GameficationModule/service/course-rewards.service.ts, src/NotificationModule/controller/notification.controller.ts
- Feedback opcional para NPS
- Salvando nps antes de iniciar gameficação
- Query que busca pelo achievement de NPS agora procura por achievement de NPS do curso específico
=> Feedback opcional para NPS
